/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalJavaScriptParser;
import org.xtext.example.mydsl.services.JavaScriptGrammarAccess;

public class JavaScriptParser extends AbstractAntlrParser {

	@Inject
	private JavaScriptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJavaScriptParser createParser(XtextTokenStream stream) {
		return new InternalJavaScriptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JavaScript";
	}

	public JavaScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JavaScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
