/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.example.mydsl.javaScript.JavaScript;
import org.xtext.example.mydsl.tests.JavaScriptInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(JavaScriptInjectorProvider.class)
@SuppressWarnings("all")
public class JavaScriptParsingTest {
  @Inject
  private ParseHelper<JavaScript> parseHelper;
  
  @Test
  public void loadString() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var t = \"teste\";");
      _builder.newLine();
      final JavaScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadInt() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var t = 12;");
      _builder.newLine();
      final JavaScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadDouble() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var t = 2.1;");
      _builder.newLine();
      final JavaScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadBoolean() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var t = true;");
      _builder.newLine();
      final JavaScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadSoma() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var t = 2 + 2;");
      _builder.newLine();
      final JavaScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loadSub() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var t = 2 - 2;");
      _builder.newLine();
      final JavaScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
