/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.javaScript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>elems</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.javaScript.elems#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.javaScript.JavaScriptPackage#getelems()
 * @model
 * @generated
 */
public interface elems extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute.
   * @see #setElements(String)
   * @see org.xtext.example.mydsl.javaScript.JavaScriptPackage#getelems_Elements()
   * @model
   * @generated
   */
  String getElements();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.javaScript.elems#getElements <em>Elements</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elements</em>' attribute.
   * @see #getElements()
   * @generated
   */
  void setElements(String value);

} // elems
