/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.javaScript;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.javaScript.JavaScriptFactory
 * @model kind="package"
 * @generated
 */
public interface JavaScriptPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "javaScript";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/JavaScript";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "javaScript";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JavaScriptPackage eINSTANCE = org.xtext.example.mydsl.javaScript.impl.JavaScriptPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.javaScript.impl.JavaScriptImpl <em>Java Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.javaScript.impl.JavaScriptImpl
   * @see org.xtext.example.mydsl.javaScript.impl.JavaScriptPackageImpl#getJavaScript()
   * @generated
   */
  int JAVA_SCRIPT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_SCRIPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_SCRIPT__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Java Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_SCRIPT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.javaScript.impl.elemsImpl <em>elems</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.javaScript.impl.elemsImpl
   * @see org.xtext.example.mydsl.javaScript.impl.JavaScriptPackageImpl#getelems()
   * @generated
   */
  int ELEMS = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMS__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>elems</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.javaScript.JavaScript <em>Java Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Java Script</em>'.
   * @see org.xtext.example.mydsl.javaScript.JavaScript
   * @generated
   */
  EClass getJavaScript();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.javaScript.JavaScript#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.javaScript.JavaScript#getName()
   * @see #getJavaScript()
   * @generated
   */
  EAttribute getJavaScript_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.javaScript.JavaScript#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.javaScript.JavaScript#getElements()
   * @see #getJavaScript()
   * @generated
   */
  EReference getJavaScript_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.javaScript.elems <em>elems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>elems</em>'.
   * @see org.xtext.example.mydsl.javaScript.elems
   * @generated
   */
  EClass getelems();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.javaScript.elems#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.javaScript.elems#getElements()
   * @see #getelems()
   * @generated
   */
  EAttribute getelems_Elements();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JavaScriptFactory getJavaScriptFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.javaScript.impl.JavaScriptImpl <em>Java Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.javaScript.impl.JavaScriptImpl
     * @see org.xtext.example.mydsl.javaScript.impl.JavaScriptPackageImpl#getJavaScript()
     * @generated
     */
    EClass JAVA_SCRIPT = eINSTANCE.getJavaScript();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JAVA_SCRIPT__NAME = eINSTANCE.getJavaScript_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JAVA_SCRIPT__ELEMENTS = eINSTANCE.getJavaScript_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.javaScript.impl.elemsImpl <em>elems</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.javaScript.impl.elemsImpl
     * @see org.xtext.example.mydsl.javaScript.impl.JavaScriptPackageImpl#getelems()
     * @generated
     */
    EClass ELEMS = eINSTANCE.getelems();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMS__ELEMENTS = eINSTANCE.getelems_Elements();

  }

} //JavaScriptPackage
