/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.javaScript;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.javaScript.JavaScriptPackage
 * @generated
 */
public interface JavaScriptFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JavaScriptFactory eINSTANCE = org.xtext.example.mydsl.javaScript.impl.JavaScriptFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Java Script</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Java Script</em>'.
   * @generated
   */
  JavaScript createJavaScript();

  /**
   * Returns a new object of class '<em>elems</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>elems</em>'.
   * @generated
   */
  elems createelems();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  JavaScriptPackage getJavaScriptPackage();

} //JavaScriptFactory
