/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.JavaScript.ui.internal.JavaScriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JavaScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JavaScriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JavaScriptActivator.getInstance().getInjector(JavaScriptActivator.ORG_XTEXT_EXAMPLE_MYDSL_JAVASCRIPT);
	}
	
}
