/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.JavaScriptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JavaScriptStandaloneSetup extends JavaScriptStandaloneSetupGenerated {
  public static void doSetup() {
    new JavaScriptStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
