/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.javaScript.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.javaScript.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JavaScriptFactoryImpl extends EFactoryImpl implements JavaScriptFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static JavaScriptFactory init()
  {
    try
    {
      JavaScriptFactory theJavaScriptFactory = (JavaScriptFactory)EPackage.Registry.INSTANCE.getEFactory(JavaScriptPackage.eNS_URI);
      if (theJavaScriptFactory != null)
      {
        return theJavaScriptFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new JavaScriptFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JavaScriptFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case JavaScriptPackage.JAVA_SCRIPT: return createJavaScript();
      case JavaScriptPackage.ELEMS: return createelems();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JavaScript createJavaScript()
  {
    JavaScriptImpl javaScript = new JavaScriptImpl();
    return javaScript;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public elems createelems()
  {
    elemsImpl elems = new elemsImpl();
    return elems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JavaScriptPackage getJavaScriptPackage()
  {
    return (JavaScriptPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static JavaScriptPackage getPackage()
  {
    return JavaScriptPackage.eINSTANCE;
  }

} //JavaScriptFactoryImpl
