/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.JavaScriptRuntimeModule;
import org.xtext.example.mydsl.JavaScriptStandaloneSetup;
import org.xtext.example.mydsl.ide.JavaScriptIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JavaScriptIdeSetup extends JavaScriptStandaloneSetup {
  @Override
  public Injector createInjector() {
    JavaScriptRuntimeModule _javaScriptRuntimeModule = new JavaScriptRuntimeModule();
    JavaScriptIdeModule _javaScriptIdeModule = new JavaScriptIdeModule();
    return Guice.createInjector(Modules2.mixin(_javaScriptRuntimeModule, _javaScriptIdeModule));
  }
}
